// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// search
List search(const int& model, const int& T, const int& max_duration, const arma::mat& A, const arma::colvec& Z, const double& m1, const double& m2, const bool& isolation, const bool& fast_search);
RcppExport SEXP CAMer_search(SEXP modelSEXP, SEXP TSEXP, SEXP max_durationSEXP, SEXP ASEXP, SEXP ZSEXP, SEXP m1SEXP, SEXP m2SEXP, SEXP isolationSEXP, SEXP fast_searchSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int& >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const int& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_duration(max_durationSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double& >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< const double& >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< const bool& >::type isolation(isolationSEXP);
    Rcpp::traits::input_parameter< const bool& >::type fast_search(fast_searchSEXP);
    __result = Rcpp::wrap(search(model, T, max_duration, A, Z, m1, m2, isolation, fast_search));
    return __result;
END_RCPP
}
// search_HI
List search_HI(const int& T, const arma::mat& A, const arma::colvec& Z, const double& m1, const double& m2);
RcppExport SEXP CAMer_search_HI(SEXP TSEXP, SEXP ASEXP, SEXP ZSEXP, SEXP m1SEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double& >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< const double& >::type m2(m2SEXP);
    __result = Rcpp::wrap(search_HI(T, A, Z, m1, m2));
    return __result;
END_RCPP
}
