# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

search <- function(model, T, max_duration, A, Z, m1, m2, isolation, fast_search) {
    .Call('CAMer_search', PACKAGE = 'CAMer', model, T, max_duration, A, Z, m1, m2, isolation, fast_search)
}

search_HI <- function(T, A, Z, m1, m2) {
    .Call('CAMer_search_HI', PACKAGE = 'CAMer', T, A, Z, m1, m2)
}

